library(tidyverse)
library(dplyr)


#--- Loaded the processed VISTA dataset generated by the read.R script ---

# Calculate the number of adults per household
households <- households %>%
  left_join(
    persons %>%
      filter(age >= 18) %>%
      count(hhid, name = "hh_adults"),
    by = "hhid"
  ) %>%
  replace_na(list(hh_adults = 0))

categories=c("NoCar","autosPerAdult_under1","autosPerAdult_over1")

households = households%>%
  mutate(hhCategory = case_when(cars == 0 ~ "noCar",
                                    cars/hh_adults < 1 ~ "autosPerAdult_under1",
                                    cars/hh_adults >= 1 ~ "autosPerAdult_over1"))

trips <- trips %>%
  left_join(
    households %>% select(hhid, hhCategory),
    by = "hhid"
  )

tripLength <- trips%>%
  mutate(across(dist1:dist9, ~ as.numeric(.x) %>% replace_na(0))) %>%
  rowwise() %>%
  mutate(dist = sum(c_across(dist1:dist9), na.rm = TRUE)) %>%
  ungroup() 

tripLength_median <- tripLength %>% 
  group_by(full_purpose,hhCategory)%>%
  summarise(
    medianTripLength = round(median(dist, na.rm = TRUE), 3),
    .groups = "drop"
  ) %>%
  spread(hhCategory,medianTripLength)

tripLength_avg = tripLength %>%
  group_by(full_purpose,hhCategory)%>%
  summarise(
    avgTripLength = round(mean(dist, na.rm = TRUE), 3),
    .groups = "drop"
  ) %>%
  spread(hhCategory,avgTripLength)

write_csv(tripLength_median,"result/Melbourne/calibration/medianTripLength.csv")
write_csv(tripLength_avg,"result/Melbourne/calibration/avgTripLength.csv")

